### PR TITLE
update device list on Firebase Test Lab

### PR DESCRIPTION
**Pull request by tarappo**
I hope to update the device list for this step because this is old information.

### CODE REVIEW

**Comment by tarappo** [comment]
I hope to fix ci/bitrise/519aa1ac2218a68f/pr, but I can not access it.
so please tell me why bitrise failed.

**Comment by tarappo** [comment]
@Szabadember 
thanks your approve.
Do I need to do anything for merge?

**Comment by godrei** [comment]
Pls update the maintenance workflow too: https://github.com/bitrise-steplib/steps-virtual-device-testing-for-ios/blob/master/maintenance/maintenance_test.go, it checks whether the current input description is up to date or not. If we do not update the test it will still show that step inputs need to be updated, even if they are updated.

**Comment by lpusok** [comment]
Thanks @tarappo,
Merged this as part of https://github.com/bitrise-steplib/steps-virtual-device-testing-for-ios/pull/20. Added maintenance test fix.
Will close as other PR is merged.

**Pull request closed without merging**
